config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get '/community', to: 'unapproved_users#unapprovedlist', as: :community
  get '/hebergements', to: 'dashboards#hebergements'
  get '/sejours', to: 'dashboards#sejours'
  get '/profile', to: 'dashboards#profile'
  get '/public_profile/:id', to: 'dashboards#public_profile', as: :public_profile

  # Search
  get '/search', to: 'flats#search'

  resources :flats do
    resources :bookings, only: [:create]
    resources :photos, only: [:new, :create, :edit, :update]
    resources :reviews, only: [:new, :create, :edit, :update]
    member do
      patch :toggle_available_status
    end
  end

  resources :unapproved_users do
    member do
      patch :activate_user_account
    end
  end

  resources :hospitals do
    resources :codes, only: [:new, :create]
  end

  resources :codes, only: [:destroy]

  root to: 'pages#home'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def hebergements
    authorize :dashboard, :hebergements?
    @userflats = Flat.where(user: current_user)

    @user = current_user

    @total_days = counting_booking_days
    @total_ppl_helped = Booking.joins(:flat).where(:flats => {:user => current_user}).group_by(&:user).count
  end

  def sejours
    authorize :dashboard, :sejours?
    @user = current_user
    @mybookings = current_user.bookings

    @currentbookings = @mybookings.select { |booking| booking.arrival < Date.today && Date.today < booking.departure }
    @futurebookings = @mybookings.select { |booking| Date.today < booking.arrival }
    @pastbookings = @mybookings.select { |booking| booking.departure < Date.today }

    @bookingstocomment = @mybookings.select { |booking| booking.departure < Date.today && Date.today < booking.departure + 1.month}
  end

  def profile
    authorize :dashboard, :profile?
    @user = current_user
  end

  def public_profile
    authorize :dashboard, :public_profile?
    @user = User.find(params[:id])
  end

  private

  def counting_booking_days
    sum = 0
    @user.flats.each do |flat|
      flat.bookings.each do |booking|
        sum += booking.booking_days
      end
    end
    return sum
  end

end

app/views/dashboards/sejours/_currentbookings.html.erb
<div class="sejours-container">
  <h1 class="yankeesblue mb-5">Séjours en cours</h1>
  <div class="row">
    <% @currentbookings.each do |booking| %>
      <div class="col-4 px-1 py-2">
        <%= link_to flat_path(booking.flat) do %>
          <div class="card-book-dashboard">
            <% if booking.flat.photo.blank? %>
              <p>Pas de photos</p>
            <% else %>
                <div class="booking-photo" style="background-image: url('<%= cl_image_path booking.flat.photo %>')"></div>
            <% end %>
            <div class="booking-description pl-2 mt-3">
              <p class="p-strip">Vous habitez actuellement chez <h4 class="h4-strip celestialblue"><%= booking.flat.user.first_name %></h4>
                (séjour du <%= booking.arrival %> au <%= booking.departure %>)</p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboards/sejours/_futurebookings.html.erb
<div class="sejours-container">
  <h1 class="yankeesblue mb-5">Séjours prévus</h1>
  <div class="row">
    <% @futurebookings.each do |fb| %>
      <div class="col-4 px-1 py-2">
        <%= link_to flat_path(fb.flat) do %>
          <div class="card-book-dashboard">
            <% if fb.flat.photo.blank? %>
              <p>Pas de photos</p>
            <% else %>
                <div class="booking-photo" style="background-image: url('<%= cl_image_path fb.flat.photo %>')"></div>
            <% end %>
            <div class="booking-description pl-2 mt-3">
              <p class="p-strip">Vous allez habité chez <h4 class="h4-strip celestialblue"><%= fb.flat.user.first_name %></h4>
                (séjour du <%= fb.arrival %> au <%= fb.departure %>)</p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/dashboards/sejours/_notifscomments.html.erb
<% @bookingstocomment.each do |booking| %>
  <%= link_to new_flat_review_path(booking.flat) do %>
    <p class="p-strip my-2 glitter">N'oubliez pas de laisser un commentaire de remerciements à <strong class="paynesgray"><%= booking.flat.user.first_name %></strong> pour votre séjour!</p>
  <% end %>
<% end %>

app/views/dashboards/sejours/_pastbookings.html.erb
<div class="sejours-container padding-bottom-100">
  <h1 class="yankeesblue mb-5">Séjours passés</h1>
  <div class="row">
    <% @pastbookings.each do |booking| %>
      <div class="col-4 px-1 py-2">
        <%= link_to flat_path(booking.flat) do %>
          <div class="card-book-dashboard">
            <% if booking.flat.photo.blank? %>
              <p>Pas de photos</p>
            <% else %>
                <div class="booking-photo" style="background-image: url('<%= cl_image_path booking.flat.photo %>')"></div>
            <% end %>
            <div class="booking-description pl-2 mt-3">
              <p class="p-strip">Vous avez habité chez <h4 class="h4-strip celestialblue"><%= booking.flat.user.first_name %></h4>
                (séjour du <%= booking.arrival %> au <%= booking.departure %>)</p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>