config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get '/community', to: 'unapproved_users#unapprovedlist', as: :community
  get '/hebergements', to: 'dashboards#hebergements'
  get '/sejours', to: 'dashboards#sejours'
  get '/profile', to: 'dashboards#profile'
  get '/public_profile/:id', to: 'dashboards#public_profile', as: :public_profile

  # Search
  get '/search', to: 'flats#search'

  resources :flats do
    resources :bookings, only: [:create]
    resources :photos, only: [:new, :create, :edit, :update]
    resources :reviews, only: [:new, :create, :edit, :update]
    member do
      patch :toggle_available_status
    end
  end

  resources :unapproved_users do
    member do
      patch :activate_user_account
    end
  end

  resources :hospitals do
    resources :codes, only: [:new, :create]
  end

  resources :codes, only: [:destroy]

  root to: 'pages#home'
end

app/controllers/unapproved_users_controller.rb
class UnapprovedUsersController < ApplicationController

  def unapprovedlist
    authorize :unapproved_user, :unapprovedlist?

    @user = current_user
    @hospital = current_user.hospital

    @beneficiaries = User.where(super_admin: false, hospital_admin: false, super_host: false, hospital: @user.hospital)
    @codes = Code.where(hospital: @user.hospital)
    @hosts = User.where(super_host: true, super_admin: false, hospital_admin: false, hospital: @user.hospital)
  end

  def activate_user_account
    authorize :unapproved_user, :activate_user_account?
    @user = User.find(params[:id])

    @user.toggle!(:approved)
    redirect_to community_path
  end


  # def edit

  # end
end

app/views/unapproved_users/index.html.erb
<table>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %>
      <td><%= user.approved %>
      <td><%= link_to "Edit", edit_unapproved_user_path(user) %>
    </tr>
  <% end %>
</table>

app/views/unapproved_users/unapprovedlist.html.erb
<div class="text-center margin-top-50 margin-bottom-50">
  <h1 class="yankeesblue">Bonjour <%= @user.first_name %>, du Centre <%= @user.hospital.hospital_name %></h1>
</div>

<div class="dashboard-content background-aliceblue padding-y-50">
  <div class="sejours-container">
    <%= render 'unapproved_users/unapprovedlist/communitybeneficiaries' %>
  </div>

  <div class="sejours-container">
    <%= render 'unapproved_users/unapprovedlist/communitycodes' %>
  </div>

  <div class="sejours-container">
    <%= render 'unapproved_users/unapprovedlist/communityhosts' %>
  </div>
</div>