config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get '/community', to: 'unapproved_users#unapprovedlist', as: :community
  get '/hebergements', to: 'dashboards#hebergements'
  get '/sejours', to: 'dashboards#sejours'
  get '/profile', to: 'dashboards#profile'
  get '/public_profile/:id', to: 'dashboards#public_profile', as: :public_profile

  # Search
  get '/search', to: 'flats#search'

  resources :flats do
    resources :bookings, only: [:create]
    resources :photos, only: [:new, :create, :edit, :update]
    resources :reviews, only: [:new, :create, :edit, :update]
    member do
      patch :toggle_available_status
    end
  end

  resources :unapproved_users do
    member do
      patch :activate_user_account
    end
  end

  resources :hospitals do
    resources :codes, only: [:new, :create]
  end

  resources :codes, only: [:destroy]

  root to: 'pages#home'
end

app/controllers/unapproved_users_controller.rb
class UnapprovedUsersController < ApplicationController

  def unapprovedlist
    authorize :unapproved_user, :unapprovedlist?

    @user = current_user
    @hospital = current_user.hospital

    @beneficiaries = User.where(super_admin: false, hospital_admin: false, super_host: false, hospital: @user.hospital)
    @codes = Code.where(hospital: @user.hospital)
    @hosts = User.where(super_host: true, super_admin: false, hospital_admin: false, hospital: @user.hospital)
  end

  def activate_user_account
    authorize :unapproved_user, :activate_user_account?
    @user = User.find(params[:id])

    @user.toggle!(:approved)
    redirect_to community_path
  end


  # def edit

  # end
end

app/views/unapproved_users/unapprovedlist/_communitybeneficiaries.html.erb
<h1 class="yankeesblue mb-5">Vos bénéficiaires</h1>
<table>
  <thead class="backgroundcolor-celestialblue">
    <tr class="padding-left-20">
      <th class=" padding-left-20 padding-right-50">Nom / Famille</th>
      <th class="padding-right-50">Email</th>
      <th class="padding-right-50">Statut</th>
      <th class="padding-right-50"></th>
    </tr>
  </thead>
  <tbody>
    <% @beneficiaries.each do |user| %>
      <tr>
        <td class=" padding-left-20 padding-right-50"><%= user.first_name %> / <%= user.family %></td>
        <td class="padding-right-50"><%= user.email %></td>
        <td class="padding-right-50">
          <% if user.approved == true %>
            <div class="backgroundcolor-aeroblue">
              <p class="p-strip textalign-center color-spanishgreen padding-x-20">Accepté</p>
            </div>
          <% end %>
        </td>
        <td class="padding-right-50">
          <% unless user.approved %>
            <%= link_to activate_user_account_unapproved_user_path(user), method: :patch do  %>
              <p class="p-strip textalign-center color-ruddybrown padding-x-20">Approuver</p>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/unapproved_users/unapprovedlist/_communitycodes.html.erb
<span>
  <div class="yankeesblue mb-5">
    <h1>Vos codes</h1>
    <%= link_to new_hospital_code_path(@hospital) do %>
      <h3>(+ Un nouveau code)</h3>
    <% end %>
  </div>
</span>

<table>
  <thead class="backgroundcolor-celestialblue">
    <tr class="padding-left-20">
      <th class=" padding-left-20 padding-right-50">Code</th>
      <th class="padding-right-50">Date de Création</th>
      <th class="padding-right-50">Statut</th>
      <th class="padding-right-50"></th>
    </tr>
  </thead>
  <tbody>
    <% @codes.each do |code| %>
      <tr>
        <td class=" padding-left-20 padding-right-50"><%= code.code %></td>
        <td class="padding-right-50"><%= code.updated_at %></td>
        <td class="padding-right-50">
          <% if code.user.nil? %>
            <div class="backgroundcolor-moccasin">
              <p class="p-strip textalign-center color-ruddybrown padding-x-20">Pas d'entrée</p>
            </div>
          <% else %>
            <div class="backgroundcolor-aeroblue">
              <p class="p-strip textalign-center color-spanishgreen padding-x-20"><%= code.user.email %></p>
            </div>
          <% end %>
        </td>
        <td class="padding-right-50"><%= link_to "Supprimer", code_path(code), method: :delete, data: { confirm: "Confirmer ?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/unapproved_users/unapprovedlist/_communityhosts.html.erb
<h1 class="yankeesblue mb-5">Vos hôtes</h1>
<table>
  <thead class="backgroundcolor-celestialblue">
    <tr class="padding-left-20">
      <th class=" padding-left-20 padding-right-50">Nom / Famille</th>
      <th class="padding-right-50">Email</th>
      <th class="padding-right-50">Statut</th>
      <th class="padding-right-50"></th>
    </tr>
  </thead>
  <tbody>
    <% @hosts.each do |user| %>
      <tr>
        <td class=" padding-left-20 padding-right-50"><%= user.first_name %> / <%= user.family %></td>
        <td class="padding-right-50"><%= user.email %></td>
        <td class="padding-right-50">
          <% if user.approved == true %>
            <div class="backgroundcolor-aeroblue">
              <p class="p-strip textalign-center color-spanishgreen padding-x-20">Accepté</p>
            </div>
          <% end %>
        </td>
        <td class="padding-right-50">
          <% unless user.approved %>
            <%= link_to activate_user_account_unapproved_user_path(user), method: :patch do  %>
              <p class="p-strip textalign-center color-ruddybrown padding-x-20">Approuver</p>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>